server:
  port: 8081
logging:
  level:
    ru.podgoretskaya: DEBUG
spring:
  datasource:
    driver_class_name:
      org.postgresql.Driver
    url:
      jdbc:postgresql://localhost:5432/deal
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: 'validate'
  liquibase:
    enabled: true
    change-log: classpath:/db/change-log-master.yaml
  main:
    allow-bean-definition-overriding: true

