spring:
  datasource:
    driver_class_name:
      org.postgresql.Driver
    url:
      jdbc:postgresql://localhost:5432/deal
  jpa:
    hibernate:
      ddl-auto: 'validate'
server:
  port: 8081
logging:
  level:
    ru.podgoretskaya: DEBUG
