spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: dossier
  datasource:
    driver_class_name:
      org.postgresql.Driver
    url:
      jdbc:postgresql://localhost:5432/deal
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: 'update'
server:
  port: 8081
logging:
  level:
    ru.podgoretskaya: DEBUG
